package vn.com.phuclocbao.exception.errorcode;

public enum PLBErrorCode {
	CAN_NOT_UPDATE_DATA,
	OUT_OF_DATE_DATA,
	CONVERTION_EXCEPTION,CAN_NOT_HASHING_PASSWORD,
	USER_CAN_NOT_BE_FOUND, OBJECT_NOT_FOUND,PASSWORD_OR_USERNAME_INCORRECT, OBJECT_ALREADY_EXIST, USER_NOT_AUTHORIZED
	;
}
